[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm --prefix backend install"]

[phases.build]
cmds = [
  "npm --prefix backend exec prisma generate",
  "npm --prefix backend run build"
]

[start]
cmd = "npm --prefix backend start"
